name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]

jobs:
  build-web:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24, 26]

    steps:
      - uses: actions/checkout@v7

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: npm install && npm run build

  dependabot:
    needs: [build-web]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    steps:
      - id: metadata
        uses: dependabot/fetch-metadata@v3
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          
      # - name: Approve Dependabot PR
      #   run: gh pr review --approve "$PR_URL"
      #   env:
      #     PR_URL: ${{ github.event.pull_request.html_url }}
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Enable auto-merge for Dependabot PRs
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
